name: right-tech-centreinc 
services:
  - name: backend
    source_dir: /backend
    github:
      branch: master 
      deploy_on_push: true
    run_command: npm start
    build_command: npm install
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /api/**
    # Add this to force Node.js 20
    environment_variables:
      - key: NODE_VERSION
        value: 20.17.0
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: CLIENT_URL
        value: https://righttechcentre.vercel.app
      # REMOVE SECRETS FROM HERE - set them in DigitalOcean dashboard instead
