name: righttechcentre-backend
region: ams3
services:
  - name: api
    source_dir: /backend
    github:
      repo: linolazarous/right-tech-centreinc
      branch: master
      deploy_on_push: true
    run_command: npm start
    build_command: npm install --legacy-peer-deps && npm run build
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    http_port: 8080
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8080"
      - key: CLIENT_URL
        value: https://righttechcentre.vercel.app
      - key: NPM_CONFIG_LEGACY_PEER_DEPS
        value: "true"
      - key: NODE_VERSION
        value: "18.x"  # Changed to 18.x for better compatibility
