name: right-tech-backend
services:
- name: api
  github:
    dir: backend # Root of the backend project
    branch: master
  build_command: cd src && npm install
  run_command: node src/server.js
  envs:
  - key: NODE_ENV
    value: production
  instance_size_slug: professional-xs
