name: SonarQube Analysis
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  Analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Analyze with SonarQube
        uses: SonarSource/sonarqube-scan-action@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Auto-injected by GitHub
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # Must be set in GitHub Secrets
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}  # e.g., "https://your-sonarqube-instance.com"
        with:
          args: >
            -Dsonar.projectKey=YOUR_PROJECT_KEY
            # -Dsonar.sources=./src   # Uncomment if sources are not in root
            # -Dsonar.tests=./tests  # Uncomment if tests exist
